# Generated by Django 4.2.11 on 2025-08-29 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('ClienteID', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=100)),
                ('Direccion', models.CharField(max_length=200)),
                ('Telefono', models.CharField(max_length=15, unique=True)),
                ('Email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
