# Generated by Django 4.2.11 on 2025-09-02 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('ProveedorID', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=100)),
                ('Contacto', models.CharField(blank=True, max_length=100, null=True)),
                ('Telefono', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('Email', models.EmailField(blank=True, max_length=100, null=True, unique=True)),
            ],
        ),
    ]
